"""
Response formatters for each support channel.

Formats the raw agent response text into channel-appropriate output
with correct length limits, tone markers, and metadata footers.
"""

from enum import Enum
from typing import Optional


class Channel(str, Enum):
    EMAIL = "email"
    WHATSAPP = "whatsapp"
    WEB_FORM = "web_form"


WHATSAPP_PREFERRED_MAX = 300
WHATSAPP_HARD_MAX = 1600
EMAIL_WORD_LIMIT = 500
WEB_FORM_WORD_LIMIT = 300


async def format_for_channel(
    response: str,
    channel: str,
    ticket_id: Optional[str] = None,
    customer_name: Optional[str] = None,
) -> str:
    """
    Format a response string for a specific support channel.

    Args:
        response: The raw response text from the agent.
        channel: The channel identifier ('email', 'whatsapp', 'web_form').
        ticket_id: Optional ticket ID for reference in email signatures.
        customer_name: Optional customer name for personalized email greetings.

    Returns:
        A formatted string appropriate for the channel.
    """
    channel_lower = channel.lower() if channel else ""

    if channel_lower == Channel.EMAIL:
        return _format_email(response, ticket_id, customer_name)
    elif channel_lower == Channel.WHATSAPP:
        return _format_whatsapp(response)
    elif channel_lower == Channel.WEB_FORM:
        return _format_web_form(response)
    else:
        # Default to web form style
        return _format_web_form(response)


def _format_email(
    response: str,
    ticket_id: Optional[str] = None,
    customer_name: Optional[str] = None,
) -> str:
    """
    Format for email channel.

    Structure:
      Hi {name},
      {response}
      Best regards,
      TechCorp Support Team
      ---
      Ticket: #{ticket_id}
      This response was generated by our AI assistant.
    """
    # Enforce word limit
    words = response.split()
    if len(words) > EMAIL_WORD_LIMIT:
        response = " ".join(words[:EMAIL_WORD_LIMIT]) + "..."

    name = customer_name if customer_name else "there"
    greeting = f"Hi {name},"

    parts = [greeting, "", response, ""]

    signature_lines = ["Best regards,", "TechCorp Support Team"]
    if ticket_id:
        signature_lines += [
            "---",
            f"Ticket: #{ticket_id}",
            "This response was generated by our AI assistant.",
        ]

    parts.extend(signature_lines)
    return "\n".join(parts)


def _format_whatsapp(response: str) -> str:
    """
    Format for WhatsApp channel.

    Truncates to preferred max of 300 chars with ellipsis, appends
    the standard reply footer. Hard limit is 1600 chars total.
    """
    footer = "\n\nReply for more help or type 'human' for live support."
    available = WHATSAPP_PREFERRED_MAX - len(footer)

    if len(response) > available:
        response = response[:available - 3] + "..."

    full_message = response + footer

    # Hard limit enforcement
    if len(full_message) > WHATSAPP_HARD_MAX:
        full_message = full_message[: WHATSAPP_HARD_MAX - 3] + "..."

    return full_message


def _format_web_form(response: str) -> str:
    """
    Format for web form channel.

    Enforces word limit and appends the support footer.
    """
    words = response.split()
    if len(words) > WEB_FORM_WORD_LIMIT:
        response = " ".join(words[:WEB_FORM_WORD_LIMIT]) + "..."

    footer = "\n\n---\nNeed more help? Reply to this message or visit support.techcorp.io"
    return response + footer


def truncate_to_channel_limit(text: str, channel: str) -> str:
    """
    Hard-truncate text to the channel's maximum length.
    Useful for validation before sending.
    """
    channel_lower = channel.lower() if channel else ""
    if channel_lower == Channel.WHATSAPP:
        if len(text) > WHATSAPP_HARD_MAX:
            return text[: WHATSAPP_HARD_MAX - 3] + "..."
    elif channel_lower == Channel.EMAIL:
        words = text.split()
        if len(words) > EMAIL_WORD_LIMIT:
            return " ".join(words[:EMAIL_WORD_LIMIT]) + "..."
    elif channel_lower == Channel.WEB_FORM:
        words = text.split()
        if len(words) > WEB_FORM_WORD_LIMIT:
            return " ".join(words[:WEB_FORM_WORD_LIMIT]) + "..."
    return text
